### PR TITLE
fixed missing row issues due to skipping heade row in each page of responses(#12)

### PR DESCRIPTION
**Pull request by nfssdq**
This PR addresses the issue in #12 . I didn't fix the issue #10 . However i have put a SkipHeaderRow field in the config which can be used to signal if it should skip the first row of the first response page. But whatever happens the first row of the subsequent pages of the query response are not skipped.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Thanks for the PR! I'd rather test against the real AWS API instead of mocks if it's convenient. How many results does it take to hit a page? Is it a static amount?

**Comment by nfssdq** [comment]
The default page size is 1000 i think. Unfortunately i don't have a test account for aws, this issue came up when trying to run some queries in my workplace, and i can't share the query or the data. so mocking seemed the easier way. please suggest some way to test it. thanks.

**Comment by tejasmanohar** [comment]
@nfssdq Got it. We need CI haha so only integration tests can be reasonably accepted. Anyhow, mocks are OK here. Merging. Thanks!

**Comment by nfssdq** [comment]
Thanks a lot for merging it.

**Pull request merged**
